spring.application.name=auth-api
server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/auth_db
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update

service.b.url=http://localhost:8081/api/transform
internal.token=default-secret